apiVersion: v1
kind: ConfigMap
metadata:
  name: mira-config
data:
  POSTGRES_NAME: mira
  POSTGRES_USER: mirauser
  DB_HOST: postgres
  DJANGO_DEBUG: "True"
  nginx.conf: |
    server {
        listen 80;
        server_name mira.intuitem.com;
        location = /favicon.ico { access_log off; log_not_found off; }
        location /static/ {
            root /usr/share/nginx/;
        }

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $http_host;
            proxy_pass http://localhost:8000;
        }
    }
