apiVersion: apps/v1
kind: Deployment
metadata:
  name: mira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mira
      rel: dev
  template:
    metadata:
      labels:
        app: mira
        rel: dev
        ver: '0.9.1l'
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      initContainers:
        - name: mira-init
          image: mira:0.9.1l
          command: ["/code/startup.sh"]
          envFrom:
          - configMapRef:
              name: mira-config
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: POSTGRES_PASSWORD
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: DJANGO_SUPERUSER_PASSWORD
      containers:
        - name: mira
          image: mira:0.9.1l
          ports:
          - containerPort: 8000
          envFrom:
          - configMapRef:
              name: mira-config
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: POSTGRES_PASSWORD
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: myvars
                key: DJANGO_SECRET_KEY
        - name: nginx
          image: nginx:latest
          ports: 
          - containerPort: 80
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
