apiVersion: apps/v1
kind: Deployment
metadata:
  name: mira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mira
      rel: dev
  template:
    metadata:
      labels:
        app: mira
        rel: dev
        ver: '0.9.1g'
    spec:
      containers:
        - name: mira
          image: mira:0.9.1g
          ports:
          - containerPort: 8000
          envFrom:
          - configMapRef:
              name: mira-config
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: POSTGRES_PASSWORD
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: myvars
                key: DJANGO_SECRET_KEY
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: DJANGO_SUPERUSER_PASSWORD

