apiVersion: apps/v1
kind: Deployment
metadata:
  name: mira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mira
      rel: dev
  template:
    metadata:
      labels:
        app: mira
        rel: dev
        ver: '0.9.1p'
    spec:
      volumes:
      - name: nginx-conf
        configMap:
          name: mira-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: startup
        configMap:
          name: mira-config
          items:
          - key: startup.sh
            path: startup.sh
            mode: 0755
      - name: staticfiles
        emptyDir:
          sizeLimit: 50Mi
      initContainers:
        - name: mira-init
          image: mira:0.9.1p
          command: ["/code/startup.sh"]
          volumeMounts:
          - name: staticfiles
            mountPath: /code/staticfiles
          - name: startup
            subPath: startup.sh
            mountPath: /code/startup.sh
          env:
          - name: POSTGRES_NAME
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: POSTGRES_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: DB_HOST
          - name: DJANGO_DEBUG
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: DJANGO_DEBUG
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: POSTGRES_PASSWORD
          - name: DJANGO_SUPERUSER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: DJANGO_SUPERUSER_PASSWORD
      containers:
        - name: mira
          image: mira:0.9.1p
          ports:
          - containerPort: 8000
          env:
          - name: POSTGRES_NAME
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: POSTGRES_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: DB_HOST
          - name: DJANGO_DEBUG
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: DJANGO_DEBUG
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: mira-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: myvars
                key: POSTGRES_PASSWORD
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: myvars
                key: DJANGO_SECRET_KEY
        - name: nginx
          image: nginx:latest
          ports: 
          - containerPort: 80
          volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
          - name: staticfiles
            mountPath: /usr/share/nginx/static
            

