apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: controller-role
rules:
- apiGroups: [""] 
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"] 
  resources: ["statefulsets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"] 
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-role-binding
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: controller
  namespace: controller
roleRef:
  kind: Role
  name: controller-role
  apiGroup: rbac.authorization.k8s.io

