apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: controller-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"] 
  resources: ["statefulsets"]
  verbs: ["get", "watch", "list"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-role-binding
  namespace: default
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: controller
  namespace: default
roleRef:
  kind: Role
  name: controller-role
  apiGroup: rbac.authorization.k8s.io

