apiVersion: v1
kind: Service
metadata:
  name: mira-cluster-controller
  namespace: controller
spec:
  type: ClusterIP
  selector:
    app: mira-cluster-controller
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
