name: Frontend Linters

on:
  pull_request:
    paths:
      - "frontend/**"

env:
  GITHUB_WORKFLOW: github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
      PUBLIC_BACKEND_API_URL: "http://127.0.0.1:8000/api"

    strategy:
      max-parallel: 4
      matrix:
        node-version: ["20"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install latest npm
        working-directory: ${{env.working-directory}}
        run: |
          npm install -g npm &&
          npm --version &&
          npm list -g --depth 0
      - name: Install dependencies
        working-directory: ${{env.working-directory}}
        run: npm ci
      - name: Run prettier check & eslint
        working-directory: ${{env.working-directory}}
        run: npm run lint
      - name: Run svelte-check
        working-directory: ${{env.working-directory}}
        run: npm run check
