name: Functional test using Playwright

on:
  push:
    branches: [ main, functional-automation ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        pip install pytest-playwright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Ensure browsers are installed
      run: python -m playwright install
    - name: Install operating system dependencies
      run: python -m playwright install-deps
    - name: Run docker
      run: |
        docker-compose up -d
    - name: Test with pytest
      run: |
        pytest asfTest
